package bfst22.vector;

import javafx.scene.paint.Color;

public enum WayType {
    UNKNOWN, LAKE, GRASS, BUILDING, RESIDENTIAL, FOREST, FARMLAND, PITCH, 
    SOCCER, PARKING, INDUSTRIAL, FARMYARD, GOLFCOURSE, PROTECTEDAREA, HEATH, 
    BEACH, RESERVE, RESORT, COASTLINE, CEMETERY, HOSPITAL, RIVER, WETLAND, 
    SAND, SCRUB, TERTIARY, MEADOW, HELIPAD, AIRPORT, PRIMARYHIGHWAY, RACEWAY, 
    RACE, APRON, VINEYARD, DESTINATION, STARTPOINT, RESIDENTIALWAY, PLACEHOLDER, FERRY, BORDER;
}