package bfst22.vector;

public enum WayType {
    UNKNOWN, LAKE, GRASS, BUILDING, RESIDENTIAL, FOREST, FARMLAND, PITCH, 
    SOCCER, PARKING, INDUSTRIAL, FARMYARD, GOLFCOURSE, PROTECTEDAREA, HEATH, 
    BEACH, RESERVE, RESORT, COASTLINE, CEMETERY, HOSPITAL, RIVER, WETLAND, 
    SAND, SCRUB, TERTIARY, MEADOW, HELIPAD, PRIMARYHIGHWAY, RACEWAY, RACE;
}
