package bfst22.vector;

public enum WayType {
    UNKNOWN, LAKE, GRASS, BUILDING, RESIDENTIAL, FOREST, FARMLAND, PITCH, SOCCER, PARKING, INDUSTRIAL, FARMYARD, GOLFCOURSE, PROTECTEDAREA, HEATH, BEACH, RESERVE, RESORT;
}
